# Workloads
workload.payments=100
workload.analytics=100

# Executor
executor.workers=2,4,8,16

# Analytics simulation
analytics.iterations=100000000

# Payment simulation
payment.sleep.ms=10

# Experiments

noise.enabled=false
noise.threads=4